### Numpy Mastery Assignment
- Answer all questions
- Submission : 20th September 2022

In [1]:
import numpy as np

1. Create a 1D array of numbers from 0 to 9

In [3]:
arr1 = np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 3x3 numpy of all True 

In [5]:
arr2 = np.full((3,3), True)
arr2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Create an array of numbers from 20 to 39

In [9]:
arr3 = np.arange(20,40)
arr3

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

4. Replace all odd numbers in Q3 by -1

In [10]:
arr3[arr3%2 != 0] = -1
arr3

array([20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34, -1, 36,
       -1, 38, -1])

5. Create two arrays of length 10 and print out  common items in both arrays

In [18]:
arr4 = np.arange(1,20,2)
arr5 = np.arange(1,20,4)
arr6 = np.intersect1d(arr4, arr5)
arr6

array([ 1,  5,  9, 13, 17])

6.  Create a 5x5 identity matrix

In [21]:
arr7 = np.arange(1,26)
arr7.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

7. In the code cell below define and print a set of arrays defined x, y and z. The array x should be take the form [10 12 9 2 20], y should have  101  values from  10  to  20  inclusive and z should be a  2×3  array of ones.

In [25]:

x = np.array([10,12,9,2,20])
y = np.linspace(10,20,101)
z = np.ones((2,3))

In [26]:
x

array([10, 12,  9,  2, 20])

In [27]:
y

array([10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ,
       11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1,
       12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2,
       13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3,
       14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1, 15.2, 15.3, 15.4,
       15.5, 15.6, 15.7, 15.8, 15.9, 16. , 16.1, 16.2, 16.3, 16.4, 16.5,
       16.6, 16.7, 16.8, 16.9, 17. , 17.1, 17.2, 17.3, 17.4, 17.5, 17.6,
       17.7, 17.8, 17.9, 18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7,
       18.8, 18.9, 19. , 19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8,
       19.9, 20. ])

In [28]:
z

array([[1., 1., 1.],
       [1., 1., 1.]])

8.Using the available Numpy functions on array x from problem  7 , find the average and the standard deviation of the value in this array. Redefine x as an array with all these values sorted in numerical order.

In [30]:
## Average
np.mean(x)

10.6

In [32]:
## standard deviation
np.std(x)

5.782732917920384

9. Create a 10x10 array with random values and find the minimum and maximum values

In [36]:
arr8 = np.random.randint(1,50,100)
arr8

array([30, 30,  7, 48, 16, 15, 40, 43, 12, 40, 36, 30,  1, 17, 47,  2,  1,
       45, 33, 45, 35, 43, 12, 37, 12, 23,  5, 32, 43, 21, 12, 12, 37, 25,
       21, 14, 41, 20, 31, 46, 45, 36, 15, 33, 23, 48, 12, 18, 13, 42, 34,
        6, 42, 47,  5, 31, 27, 10, 31, 19, 15, 33, 17, 27, 12, 35, 27, 17,
       12,  9, 42, 35,  6, 24, 12, 43, 47, 41, 10, 13, 22, 18, 38, 48, 48,
       43, 15, 13, 35, 49, 18, 25,  2, 44, 21, 49, 20, 39,  4, 31])

In [38]:
arr8.reshape(10,10)

array([[30, 30,  7, 48, 16, 15, 40, 43, 12, 40],
       [36, 30,  1, 17, 47,  2,  1, 45, 33, 45],
       [35, 43, 12, 37, 12, 23,  5, 32, 43, 21],
       [12, 12, 37, 25, 21, 14, 41, 20, 31, 46],
       [45, 36, 15, 33, 23, 48, 12, 18, 13, 42],
       [34,  6, 42, 47,  5, 31, 27, 10, 31, 19],
       [15, 33, 17, 27, 12, 35, 27, 17, 12,  9],
       [42, 35,  6, 24, 12, 43, 47, 41, 10, 13],
       [22, 18, 38, 48, 48, 43, 15, 13, 35, 49],
       [18, 25,  2, 44, 21, 49, 20, 39,  4, 31]])

In [39]:
## Minimum
np.min(arr8)

1

In [40]:
## Maximum
np.max(arr8)

49

10. Create a 3x3 matrix with values ranging from 0 to 8

In [45]:
arr9 =np.matrix(np.arange(0,9))
arr9

matrix([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [46]:
arr9.reshape(3,3)

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

11.  Generates an array [[1 2 3] [4 5 6]]

In [64]:
arr10 = np.array([[1, 2, 3], [4, 5, 6]])
arr10

array([[1, 2, 3],
       [4, 5, 6]])

12. Generates an array [0 2.5 5 7.5 10]

In [59]:
arr11 =np.arange(0,11,2.5)
arr11

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

13. Generates an 3x3 array of zeros

In [61]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

14. Create array from 0.1 to 10 with 12 elements, inclusively

In [62]:
arr12 = np.linspace(0.1,10,12)
arr12

array([ 0.1,  1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1,
       10. ])

15. Create a matrix with seven columns and five rows of ten(10).

In [65]:
arr13 = np.full((5,7), 10)
arr13

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

16. What is the difference between numpy and list?

Answer:

NumPy arrays are more efficient in terms of memory usage compared to lists.

17. Create a 1D array of ones consisting of  50  values. Change the values of the array so that the values alternate between ones and zeros ie  1,0,1,0,1,0,1,0,1...  ensuring that the starting value is  1 

In [71]:
arr14 = np.ones(50)

arr14[1::2] = 0

arr14[0] = 1

print(arr14)

[1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.
 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.
 1. 0.]


18. Generate a  10×10  matrix of zeros.
Make this matrix an identity matrix

In [72]:
arr15 = np.zeros((10, 10))

np.fill_diagonal(arr15, 1)

print(arr15)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


19. Generate an array x to be a  10×10  array of zeros. Redefine its diagonal components (from left to right) to equal one

In [74]:
arr16 = np.zeros((10, 10))

for i in range(10):
    arr16[i, i] = 1

print(arr16)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


20. What is the dot products of this two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [130]:
arr17 = np.matrix([[1,2],[3,4]])
arr18 = np.matrix([[5,6],[7,8]])

In [131]:
arr17 * arr18

matrix([[19, 22],
        [43, 50]])

21.  Multiply these two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [80]:
arr19 = np.matrix([[1,2],[3,4]])
arr20 = np.matrix([[5,6],[7,8]])
multiply = arr19 * arr20
multiply

matrix([[19, 22],
        [43, 50]])

22. Multiply this matrix  [[1,2],[3,4]] by a  scalar value of 5

In [82]:
a = 5
arr21 = np.matrix([[1,2],[3,4]])

scal = a * arr21
scal

matrix([[ 5, 10],
        [15, 20]])

23. A = [[1,2],[3,4]] and B = transpose of A. Calculate AxB

In [126]:
A = np.array([[1,2],[3,4]])
B = np.transpose(A)

In [127]:
A

array([[1, 2],
       [3, 4]])

In [128]:
B

array([[1, 3],
       [2, 4]])

In [129]:
A * B

array([[ 1,  6],
       [ 6, 16]])

24. A= [[1,2],[3,4]] and B =  [[5,6],[7,8]]. Is A x B = B x A ? Show working

In [90]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [99]:
A * B

array([[ 1,  6],
       [ 6, 16]])

In [100]:
B * A

array([[ 1,  6],
       [ 6, 16]])

25. Creates an array [[0 1 2] [3 4 5]]
- Let A = first row of the matrix
- B = second row of the matrix
- C = second column of the Matrix
- D = first row, third column of the matrix
- print A , B , C, D

In [107]:
arr22 = np.matrix([[0, 1, 2], [3, 4, 5]])
arr22

matrix([[0, 1, 2],
        [3, 4, 5]])

In [116]:
A = arr22[0,:]
A

matrix([[0, 1, 2]])

In [117]:
B = arr22[1,:]
B

matrix([[3, 4, 5]])

In [118]:
C = arr22[:,1]
C

matrix([[1],
        [4]])

In [121]:
D = arr22[0,2]
D

2